### ISSUE TITLE
Generate pages without corresponding file

### ISSUE THREAD

**Issue by jboynyc** [staticjinja/staticjinja#124]
As I understand it, every page that staticjinja generates must have a corresponding file on disk, whether a template file or another source file with corresponding rendering rule. It would be neat if there was a way to generate pages solely on the basis of data structures defined in the build script, which might all use the same generic template (such as `_post.html`). 

Is my understanding correct that such a thing is not currently possible? And would there be any interest in adding support for it?

**Comment by NickCrews** [comment]
Hi! Thanks for reaching out. I think I see what you mean, are you talking about something similar to https://github.com/staticjinja/staticjinja/issues/72? I believe what you request is currently possible using a custom render function, though it's not super nice. See https://github.com/staticjinja/staticjinja/issues/72#issuecomment-727076869 for more info. Will that work for you?

**Comment by jboynyc** [comment]
I think you're right @NickCrews, that should accomplish what I am describing. I'll give it a shot. Thanks!
