### ISSUE TITLE
jinja2 <4 support

### ISSUE THREAD

**Issue by fgaz** [staticjinja/staticjinja#158]
[3.0.x is out](https://jinja.palletsprojects.com/en/3.0.x/changes/#version-3-0-1)

**Comment by NickCrews** [comment]
Hi @fgaz. I'm not sure what you are looking for here. I think staticjinja should be compatible with both jinja 2.x and 3.x. If you want to use jinja 3.x in your project, go ahead and do that, I don't think you should have any problem. Have you encountered a problem when using jinja 3.x?

**Comment by fgaz** [comment]
I may be mistaken, but doesn't this line mean that only `jinja2 < 3` is supported?

https://github.com/staticjinja/staticjinja/blob/dcfcaf88f02e2e9494fcc64bfa25e36ea53a46f2/pyproject.toml#L38

**Comment by NickCrews** [comment]
Oops I didn't understand the caret modifier. Indeed, you're right. I think the solution is to change the caret to a >. I'll double check that this doesn't have any unintended consequences.

**Comment by fgaz** [comment]
`>= 2.10.1, < 4` is also ok and signals that jinja 4 is not yet supported (since it does not exist yet and it isn't kn own if it'll break staticjinja). not sure if upper version bounds are common in the python ecosystem.

**Comment by NickCrews** [comment]
This gives a good reason why you should specify an upper bound. https://python-poetry.org/docs/faq/#why-are-unbound-version-constraints-a-bad-idea

Your suggestion above is I think what we want. That PR contains that
