### ISSUE TITLE
How to render a output file from the database value? 

### ISSUE THREAD

**Issue by rajasimon** [staticjinja/staticjinja#162]
I don't want the markdown way to generate the output build but need to generate the output using the db record. 

```
def handle(self, *args, **options):
    article_id = options["article_id"]

    article = Article.objects.filter(id=article_id).first()
    contexts = (r"{}".format(article.id), self.db_context)
    rules = (r"{}".format(article.id), self.render_db)
    site = Site.make_site(
        searchpath="/Workspace/blogstreak/blogstreak/core/staticjinja",
        outpath="/Workspace/blogstreak/output",
        contexts=[contexts],
        rules=[rules],
    )
    site.render()
```

I have these but it's not working. Anyone knows how to do this properly. ?

**Comment by NickCrews** [comment]
Hey @rajasimon! Sorry I didn't see this earlier. Could you post the error that you're seeing? I don't know what "not working" means, could you explain what you want to happen, and what is happening instead? Also you might have to include the contents of `self.db_context` and `self.render_db`. Thanks!

**Comment by NickCrews** [comment]
Closing due to inaction, please reopen if you still need help.
