### ISSUE TITLE
Replace `easywatch` with something else

### ISSUE THREAD

**Issue by webknjaz** [staticjinja/staticjinja#186]
That project doesn't ship wheels, and sdist builds emit setuptools warnings because it uses deprecated features. When running `python -Werror pip install staticjinja`, it turns said warnings into errors.
I'm suggesting to replace the dependency as that project was last updated 5 years ago and might now issue a fix in the near future.
While I can opt out of turning these warnings into errors for now, on my side, those warnings will turn into errors for everyone this fall, in just a few months. I think, it's wise to act proactively.

**Comment by webknjaz** [comment]
Filed an upstream issue too: https://github.com/Ceasar/easywatch/issues/12.

**Comment by NickCrews** [comment]
Thanks for the issue! I agree something must be done. I think the best path is to just vendor in https://github.com/Ceasar/easywatch/blob/master/easywatch/easywatch.py, that appears to be the entirety of the code! The underlyting lib, [watchdog](https://github.com/gorakhargosh/watchdog), appears to be well-maintained.

**Comment by NickCrews** [comment]
@webknjaz This should be fixed for you in 5.0.0. If you do `pip install staticjinja==5.0.0` do you still get the warning?

**Comment by webknjaz** [comment]
@NickCrews wow, thanks! I'll alert my colleague who is integrating this lib.

By the way, I noticed that some ecosystem projects integrated Watchman:
https://adamj.eu/tech/2021/01/20/efficient-reloading-in-djangos-runserver-with-watchman/ / https://www.youtube.com/watch?v=IghyoR6ld60. FYI in case you ever end up needing to rethink this feature.

P.S. I noticed that you are using a long-outdated version of my pypi-publish GitHub Action (many other actions look outdated too, for that matter) and are relying on long-living PyPI API tokens. May I invite you to upgrade the action and switch to tokenless trusted publishing? The doc is here https://docs.pypi.org/trusted-publishers/ and the change is pretty straightforward: https://github.com/marketplace/actions/pypi-publish#trusted-publishing.

**Comment by NickCrews** [comment]
Oh, yes! I've used trusted publishers before, but I just haven't done that here. Will do.

**Comment by oraNod** [comment]
Hi @NickCrews Thanks a mill for the quick fix. I've upgraded `staticjinja` to 5.0.0 but still notice there's an exception related to `setuptools`. Here are some [logs](https://pipelines.actions.githubusercontent.com/serviceHosts/580826dc-c978-43ce-933d-5bf0efc7311a/_apis/pipelines/1/runs/21/signedlogcontent/2?urlExpires=2023-08-17T10%3A44%3A22.2315898Z&urlSigningMethod=HMACV1&urlSignature=LG9xWgAeb8hO0gLYZ8C7isNt9xv0Qw4DBTt97nVH0pQ%3D) that might give you some info.

**Comment by webknjaz** [comment]
@oraNod that's not related to this project anymore: https://github.com/ansible/docsite/pull/182/files#r1297191664

**Comment by oraNod** [comment]
Thanks for the heads up @webknjaz and apologies for the noise here @NickCrews cheers!
