### ISSUE TITLE
How to handle data files and dependencies?

### ISSUE THREAD

**Issue by sahuguet** [staticjinja/staticjinja#43]
I am using data files (e.g. json, yaml) to load some data into the context of the templates.
I would like the templates to be regenerated when the data files change.
I don't see any way of doing that.

**Comment by Ceasar** [comment]
Very reasonable idea for a feature, but something that *is* missing. Any ideas for how to make this change?

**Comment by sahuguet** [comment]
There are two issues:
1- detecting change & dependency
2- reloading the data and making it available

== Option A ==
For 1, we could imagine having a special folder for data.
The watcher would keep checking there and would create the right dependencies.

For 2, we could have a special template file _data.html that would load the data into a bunch of global variables.
{% set my_data = load_data() %} where load_data is a function added to the Jinja env (http://jinja.pocoo.org/docs/dev/api/#jinja2.Environment.globals).

== Option B ==
We still need to detect a data change.
We use some watcher events to recompute the data.
I don't fully understand how events work yet.

== Option C ==
something else.

**Comment by NickCrews** [comment]
Either the current reloader feature solves this, or this request is so old it's irrelevant now. Closing, feel free to reopen/open another issue if this is still relevant.
