### ISSUE TITLE
Figure out how to version docs

### ISSUE THREAD

**Issue by Ceasar** [staticjinja/staticjinja#55]
The docs are presently out of date. Would be worthwhile to figure out how to pin the docs to specific versions.

**Comment by Ceasar** [comment]
In the meantime, people can just tags. The docs are not too complicated. https://github.com/Ceasar/staticjinja/releases

**Comment by NickCrews** [comment]
I think this is taken care of now. You can view the different versions of the docs at  https://readthedocs.org/projects/staticjinja/versions/, although this only goes back not very far...
