### ISSUE TITLE
Compilation rule example

### ISSUE THREAD

**Issue by PatrickMassot** [staticjinja/staticjinja#87]
The example at https://staticjinja.readthedocs.io/en/latest/user/advanced.html#compilation-rules is completely outdated. It refers to http://silas.sewell.org/blog/2010/05/10/jinja2-markdown-extension/ which self-flags as unmaintained and is not compatible with python3. 

I can provide an updated markdown extension if needed. 

Another old problem with this compilation rule thing is the custom renderer doesn't seem to have any access to the staticjinja output path.

**Comment by NickCrews** [comment]
Whoops, missed this until now.

Yes, this should be fixed. Simply removing the example would be OK with me, but I think keeping a markdown example might be nice. If you want to take the initiative and submit a PR for adding an up-to-date extension that would be great! Otherwise I may get to it sometime.

Regarding the compilation rule, I need to think about it more, but I do agree that it is clunky. I wonder if we could get away with not even having it, and just using jinja builtins like filters and macros? Also, although the custom renderer doesn't have access to the staticjinja output path directly, you can get it through `env.outpath`. That's what I currently do in my custom script, but I don't like it...

**Comment by PatrickMassot** [comment]
I'm sorry I don't have much time to open a PR, but here is a translation of the existing example so that it does not rely on an external Jinja2 extension. It uses the mistletoe markdown renderer, but changing that is very easy.
```python
#!/usr/bin/env python3
from pathlib import Path

import jinja2  
import jinja2.ext  
from mistletoe import Document, HTMLRenderer  
  
from staticjinja import Site  
  
class MarkdownExtension(jinja2.ext.Extension):  
    tags = set(['markdown'])  
  
    def __init__(self, environment):  
        super().__init__(environment)  
        environment.extend(markdowner=HTMLRenderer())  
  
    def parse(self, parser):  
        lineno = next(parser.stream).lineno  
        body = parser.parse_statements(  
            ['name:endmarkdown'],  
            drop_needle=True  
        )  
        return jinja2.nodes.CallBlock(  
            self.call_method('_markdown_support'),  
            [],  
            [],  
            body  
        ).set_lineno(lineno)  
  
    def _markdown_support(self, caller):  
        return self.environment.markdowner.render(Document(caller())).strip()  

ROOT = Path(__file__).parent

def render_post(env, template, **kwargs):
    """Render a markdown template to HTML."""
    post_template = env.get_template("_post.html")
    path = Path(template.name)
    post_template.stream(**kwargs).dump(str((ROOT/'build'/path).with_suffix('.html')))

def get_post_contents(template):
    return {'post': Path(template.filename).read_text()}

site = Site.make_site(
        searchpath=ROOT/'templates',
        outpath=ROOT/'build',
        extensions=[MarkdownExtension],  
        rules = [('.*.md', render_post)],          
        contexts=[('.*.md', get_post_contents)],)
  
site.render()
```
In addition to this python file, you need a templates folder containing a `_base.html` and the `_post.html` from the current doc, and a bunch of `.md` files, maybe in subfolders of `templates`.

Note however that this method using a Jinja2 extension is a bit silly. You can also define a Jinja2 filter `markdown` with a lot less lines of code, and just replace from `_post.html` the 
```
{% markdown %}
{{ post }}
{% endmarkdown %}
```
by `{{ post | markdown }}`.

**Comment by NickCrews** [comment]
I finally got around to this :)

Please see #102 for my proposed fix.
