### ISSUE TITLE
Rules: Wrong parameter for function

### ISSUE THREAD

**Issue by larsschwegmann** [staticjinja/staticjinja#90]
Hey! I noticed that the docs for custom rules say: 

> rules – A list of regex, function pairs used to override template compilation. regex must be a regex which if matched against a filename will cause function to be used instead of the default. function must be a function which takes **a Jinja2 Environment**, the filename, and the context and renders a template.

But the function is actually called like this:

`rule(self, template, **context)` -> [staticjinja.py, Line 371](https://github.com/Ceasar/staticjinja/blob/master/staticjinja/staticjinja.py#L371)

`self` is a staticjinja `Site`, not a `jinja2.Environment`. For my usecase, I need access to the Environment so that I can access globals defined in that environment.

**Comment by NickCrews** [comment]
oooooh, you're right.

Since a `Site` contains a reference to `_env`, you can get to the `Jinja2.Environment` via `self._env`. I recently inherited this project, and I'm not sure why `_env` has the leading underscore, if it really is a private variable that you shouldn't be accessing. From an initial scan through the code, I don't think it needs to be private. It should be renamed to `env`, and you should be fine accessing it directly. To be safe, what are you looking to access in the environment? I'm wondering if maybe `Site` needs some wrapper function to access that part of `_env` safely.

**Comment by larsschwegmann** [comment]
For context, here's what I'm trying to do:

I create the Site as follows:

```python
site = Site.make_site(
        searchpath='templates',
        outpath='build',
        env_globals={
            'language': 'de',
        },
        contexts=[('app.html', context)],
        rules=[('posts/*', render_post)],
    )
```

Inside the `render_post`function, I get these 3 params:

`env` (which is actually a `Site`), `template` and `**context`.
I want to access the global `language` that I defined in `env_globals`. AFAIK this is stored in  [jinja2.Environment.globals](https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.Environment.globals). That is why I need access to the environment.

**Comment by larsschwegmann** [comment]
accessing `env._env.globals['language']`python worked by the way. But I guess it would make sense to remove the underscore or add an accessor function. And also update the docs for the rules 😄

**Comment by NickCrews** [comment]
Hey @larsschwegmann, thanks for the extra info and the PR. Sorry I was so slow on this, that must have been frustrating.

The PR looks great, I can't think of a reason why making `env` public would be bad. Thanks for the docs fix too. As an aside I also noticed that the docs are incorrect in another way, they say the function is given the `template.name`, but actually it is given the `template`. I'll fix that docs error in a follow up commit though, don't worry about that here.

During my diggings into the intended use-case for `env_globals`, I found PR #70 that contains commit https://github.com/staticjinja/staticjinja/pull/70/commits/004479707f4853f394da41d71ce4933e3860c4ed. Are you doing what the example shows, using `{{language}}` inside some `template1.html`? Or are you just using that config in your `render_post()` custom function? If it's the latter I wonder if there is a better way to pass in that config that is external to Jinja. I'm not positive, but I think that `env.globals` is intended to expose configs for templates to use, not as much for your external python code. On the other had, if it works then you probably don't want/need to have to think about it too hard :)

**Comment by NickCrews** [comment]
I'm closing this because the PR was merged, but if you want to keep talking about my above thoughts then please do :)

**Comment by larsschwegmann** [comment]
Hey @NickCrews no problem, I was quite busy in the last weeks as well! Thank you for merging!

I'm actually using it both in templates and in a custom function, that is why I thought it would be handy to be able to access the env_globals that I already had defined. 😄 

Would it be possible for you to create a new release on pip?

**Comment by NickCrews** [comment]
Sure, sounds like a good use for it then!

I've been slowly taking over maintainer responsibilities for this project and just got the privileges for pushing to pip. It might take a bit for me to figure out how to do that on this new project, but will try to do that in a week or so.
