### ISSUE TITLE
Problem with documentation Compilation Rules example

### ISSUE THREAD

**Issue by garyrob** [staticjinja/staticjinja#91]
The example for converting markdown files has a function:

`def render_post(env, template, **kwargs)`

But the body of the function never uses the `template` arg, and in my experimenting with the code, it seems to not actually process markdown files. So, it appears to me that the documentation code is simply wrong.

**Comment by PatrickMassot** [comment]
This is not the only issue with this doc, see #87.

**Comment by NickCrews** [comment]
I've been talking to the previous maintainer @Ceasar to get admin access to ReadTheDocs, and just got them. So hopefully I can actually start tackling these issues now...

**Comment by NickCrews** [comment]
I finally got around to this :)

Please see #102 for my proposed fix.
