### ISSUE TITLE
Problem with static files

### ISSUE THREAD

**Issue by biro-mark** [staticjinja/staticjinja#97]
The docs say to use the --static flag to serve static files https://staticjinja.readthedocs.io/en/latest/user/quickstart.html?highlight=static#configuration. 

Here's what I tried
`staticjinja watch --static static`

I get this warning
 `env/lib/python3.6/site-packages/staticjinja/staticjinja.py:97: UserWarning: staticpaths are deprecated. Use Make instead.
  warnings.warn("staticpaths are deprecated. Use Make instead.")`

And my static files under `templates/static` were not copied

**Comment by NickCrews** [comment]
The docs are out of date currently, sorry.

In https://github.com/staticjinja/staticjinja/issues/58 the old maintainer of this project, Caesar, decided that copying static files was out of scope of this project. He added that warning, _but_ I'm reading through the commit history, I don't _think_ that feature was ever removed. I tried using your example command above, and although I got that same warning, the files were indeed copied. Did you just install the latest package from PyPi with `pip3 install staticjinja`? Can you double check everything else on your end, such as maybe you don't have permissions to create directories?

Also, as noted in that above issue, I have plans (...that I haven't gotten to in 6 months so who knows when I will...) to change how this library looks for/classifies files, so be aware of that.

**Comment by biro-mark** [comment]
Yeah I got it through pip. Thanks for looking into the issue and sorry for the accidental double post. I'm not sure what happened on my end and now I'm using a different library that does have the file copying functionality.

**Comment by NickCrews** [comment]
Relevant: https://github.com/staticjinja/staticjinja/issues/58
